[project]
name = "bricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
"numpy",
"pandas",
"opencv-python",
]

[tool.pyright]
reportAttributeAccessIssue = false
reportGeneralTypeIssues = false
